<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = [
            'WIFI CAL',
            'MBM',
            'PACKING',
            'TP',
            'IOT',
            'DOWNLOAD',
            'FINAL TEST',
            'RF CAL',
            'AUTO SCREW',
            'NEW SETUP',
            'FTTS',
            'ARFTS',
            'IR TEST',
            'MOCA',
            'NVM',
            'THROUGHPUT',
            'JIG A',
            'MAPPING',
            'AUTOSCREWING',
            'JIG 3',
            'JIG 4',
            'TESTING',
            'BARCODE',
            'OBA',
            'CPTC',
            'TS REPAIR',
            'HEATSINK',
            'LED CHECK',
            'VISUAL INSPECTION',
            'AFTS',
            'MBPS',
            'OLD',
            'ASSEMBLY',
            'ALL LINES',
            'JIG MODIFICATION',
            'MULTI',
            'WC',
            'OTA',
            'AFTS 2',
            'CALIBRATION',
            'PKI',
            'ALL LINE AUTO SCREW',
            'SET UP',
            'VGA',
            'BIOMETRICS REPAIR',
            'TRANSFER',
            'SCREW DETECTION',
            'REWORKS',
            'JIG 5',
            'JIG 6',
            'JIG 7',
            'HDMI',
            'JIG 2',
            'FFTS',
            'TROPOT',
            'WF',
            'CAN SHIELD',
            'NEW MODEL',
            'CAMERA TEST',
            'LOCK BOTSHELL',
            'POWER CHECK',
            'POWERCHECK',
            'INPUT',
            'MOCS',
            'FTTS 2',
            'WEIGHING',
            'MIS',
            'PC',
            'FINAL CHECK',
            'ESD',
            'OLD FROM JIG',
            'PCIE BAND',
            'FIXTURE MODIFICATION',
            'MAPING',
            'SDS',
            'OFFICE',
            'JIG  4',
            'ARFTS/FTTS',
            'RETURN TO WH',
            'BORROWED',
            'SCREWING',
            'MULTI NEW SET UP',
            'All process',
            'FINAL LOOP',
            'WC CAL',
            'FACILITIES USE',
            'FINAL STATION',
            'SCANNING',
            'FINAL',
            'TRANSFER TO PSITE',
            'ARUBA',
            'ONLINE PRINT',
            'HDMI 1',
            'FAN CHECK',
            'OUT PROCESS',
            'TS Engr.',
            'OLD FROM REPAIR',
            'FUSING',
            'PARTS SIMULATION AND LIFE SPAN DATA',
            'PRI TRANSFER',
            'SCREW ATTACH',
            'REPAIR',
            'MACHINE COVER',
            'RP',
            'SCREW CHECK',
            'PROJECT 6',
            'CONVEYOR',
            'MATHEW',
            'FG',
            'ARFTS 10',
            '2M STATION',
            'BIND',
            'SMT',
            'QA',
            'IOT/MAPPING',
            'FROM REPAIR',
            'MAKE NEW FIXTURE',
            'SP',
            'ARFTS 2',
            'NEW',
            'FTSS',
            'BOTSHELL',
            'SORTING',
            'JIG 1',
            'FT',
            'EQUIPMENT',
            'MANUAL SCREW',
            'RF CALIBRATION',
            'WIFI CALIBRATION',
            'FOR REPAIR',
            'MANUAL SCREWING',
            'SET',
            'CALIBRATE',
            'AGUSTUS',
            'GST FABRICATION',
            'SERVER ROOM',
            'SET UP FENWAY',
            'SET UP AGUSTUS',
            'NEW SAMPLE',
            'LED AND FUSE',
            'MES',
            'PC REPAIR',
            'MULTI STATION',
            'LASER PRINT',
            'Pi 4GB',
            '1 PACK',
            'FOR PSITE ENGR.',
            'AUGUSTUS',
            'WEIGHING STATION',
            'FINAL VISUAL INSPECTION',
            'MT01',
            'FUSE TEST',
            'FOR POWER SUPPLY OF WATER DISPENCER',
            'TS TESTING',
        ];
        foreach ($names as $name) {
            DB::table('stations')->insert([
                'name' => $name
            ]);
        }
    }
}
